config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index', as: :tasks
  get 'tasks/new', to: 'tasks#new', as: 'new_task'
  get 'tasks/:id', to: 'tasks#show', as: 'task'
  post 'tasks',    to: 'tasks#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
    @complete = checked?
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.new(task_params)
    task.save

    redirect_to task_path(task)
  end

  private
    def checked?
      if @task.completed
      return "this task is complete"
      else
      return "this task is not complete"
      end
    end


  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>
<ul>
    <% @tasks.each do |task| %>
   <li> <%= link_to task.title, task_path(task) %> </li>
    <% end %>
</ul>

app/views/tasks/new.html.erb
<h1>New task</h1>
<%= form_for @task do |f| %>
  <%= f.label :title %> <%= f.text_field :title %>
  <%= f.label :details %> <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

  <p> <%= link_to 'back to list',  tasks_path %></p>

app/views/tasks/show.html.erb
<ul>
  <li> <%= @task.title %> </li>
</ul>

<p> <%= @task.details %> </p>

<p> <%= @complete %> </p>

<p> <%= link_to 'back to list',  tasks_path %></p>